### ISSUE TITLE
cstaff 登录后，网站左上角标题和tab页标题改为网点名

### ISSUE THREAD

**Issue by voyax** [talent-land-private/.github#38]
这个信息最好从 token payload 里带出来作为用户基本信息，存储在 localstorage 中，不单独调用接口

**Comment by iyolee** [comment]
登录成功，如果有网点信息接口能返回吗 @zhuminchosen

**Comment by zhuminchosen** [comment]
>

**Comment by zhuminchosen** [comment]
> 登录成功，如果有网点信息接口能返回吗 @zhuminchosen

可以，已经加上了
